
`offline` loader is currenly unavailable cause github and pypi maximum file size limit.
